spring:
  application:
    name: chatting
  datasource:
    url: jdbc:h2:mem:chat
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  swagger-ui:
    path: api
    tags-sorter: alpha
    operations-sorter: alpha
  paths-to-match:
    - /**
jwt:
  secret: "c3ByaW5nLWJvb3Qtc2VsZi1wcm9qZWN0LWlzLWJsb2ctc2VydmljZS1sb2NhbAo="
  expiration: 360000000
